name: Node.js CICD

on:
  push:
    branches:
      - main

jobs:
  build-and-push: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build the docker image
        run: docker build -t nodejs-image_amira .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to Docker Hub
        run: |
          docker tag nodejs-image_amira ${{ secrets.DOCKER_USERNAME }}/nodejs-image_amira:latest
          docker push ${{secrets.DOCKER_USERNAME }}/nodejs-image_amira:latest

  test:
    runs-on: ubuntu-latest 
  
    steps:
        - name: Checkout repository 
          uses: actions/checkout@v2
        
        - name: Install dependencies
          run: npm install
      
        
        - name: Run integration tests
          run: npm run test:integration
        
        - name: Generate test report
          run: npx mocha --reporter mocha-junit-reporter > test-report.xml
        
        - name: Upload test report
          if: always()
          uses: actions/upload-artifact@v2
          with:
           name: test-report  
           path: test-report.xml

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to EC2 AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-image_amira:latest
            sudo docker stop nodejs-image_amira || true
            sudo docker rm nodejs-image_amira || true
            sudo docker run -d -p 3002:3000 --name=nodejs-image_amira ${{ secrets.DOCKER_USERNAME }}/nodejs-image_amira:latest
            sudo docker ps
