name: Node.js CI

on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build the docker image
        run: docker build -t nodejs-image_finalee .

      - name: Log in the dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to Dockerhub
        run: |
          docker tag nodejs-image_finalee ${{ secrets.DOCKER_USERNAME }}/nodejs-image_finalee:latest
          docker push ${{secrets.DOCKER_USERNAME }}/nodejs-image_finalee:latest


  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to EC2 AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
          
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-image_finalee:latest
            
           
            sudo docker run -d -p 3008:3000 --name cc nodejs-image_finalee ${{ secrets.DOCKER_USERNAME }}/nodejs-image_finalee:latest
            sudo docker ps 
